service: octoprint-listener
org: andresmweber
app: my-first-app
plugins:
  - serverless-dotenv-plugin
  - serverless-plugin-git-variables
  - serverless-offline
  - serverless-bundle
  - serverless-export-env
provider:
  name: aws
  runtime: nodejs12.x
  profile: aw-serverless
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  memorySize: 512
  tags:
    GLOBAL-TAG2: bar
  environment:
    DEBUG: ${env:DEBUG, ''}
    SLS_DEBUG: ${env:SLS_DEBUG, ''}
    REGION: ${self:provider.region}
    STAGE: ${env:STAGE, self:provider.stage}
    BASE_URL: ${self:custom.apiEndpoints.${git:branch}, self:custom.apiEndpoints.${self:provider.stage}, self:custom.resourcesStages.dev}
    SLACK_URL: ${ssm:/aw/slack/octoprint~true}
    BUCKET: ${self:custom.BUCKET}
    GIT_COMMIT_LONG: ${self:custom.GIT_COMMIT_LONG}
    GIT_TAGS: ${self:custom.TAGS}
    GIT_IS_DIRTY: ${self:custom.GIT_IS_DIRTY}
    GIT_BRANCH: ${self:custom.GIT_BRANCH}
    GIT_REPOSITORY: ${self:custom.GIT_REPOSITORY}
    GIT_DESCRIPTION: ${self:custom.GIT_DESCRIPTION}

package:
  include:
    - lambdas/**
  exclude:
    - ./node_modules/
    - tests/**
  individually: true

custom:
  gitDescription: ${git:repository} - ${git:branch} - ${git:tags}
  BUCKET: octoprint-listener-snapshot-${self:provider.stage}-bucket
  GIT_COMMIT_LONG: ${env:GIT_COMMIT_LONG, git:sha1}
  GIT_TAGS: ${env:TAGS, git:tags}
  GIT_IS_DIRTY: ${env:GIT_IS_DIRTY, git:isDirty}
  GIT_BRANCH: ${env:GIT_BRANCH, git:branch}
  GIT_REPOSITORY: ${env:GIT_REPOSITORY, git:repository}
  GIT_DESCRIPTION: ${env:GIT_DESCRIPTION, git:describe}
  apiEndpoints:
    prod: https://www.example.com/api/prod
    dev: https://www.example.com/api/dev
    master: https://www.example.com/api/master

iamRoleStatements:
  - Effect: 'Allow'
    Action:
      - 's3:ListBucket'
    Resource: { 'Fn::Join': ['', ['arn:aws:s3:::', { 'Ref': 'OctoprintSnapshotBucket' }]] }
  - Effect: 'Allow'
    Action:
      - 's3:PutObject'
    Resource:
      Fn::GetAtt: [OctoprintSnapshotBucket, Arn]

functions:
  receiveWebhook:
    handler: src/lambdas/receiveWebhook.handler
    description: ${self:custom.gitDescription}
    events:
      - http:
          path: webook
          method: POST
          cors: true
    environment:
      BUCKET: !Ref OctoprintSnapshotBucket
  getUser:
    handler: src/lambdas/getUser.handler
    description: ${self:custom.gitDescription}
    events:
      - http:
          path: get-user/{ID}
          method: GET
          cors: true

# you can add CloudFormation resource templates here
resources:
  Description: >
    ${self:service} ${git:branch}:${git:sha1}
    https://github.com/andresmweber/octoprint-listener
    ${git:message}
  Resources:
    OctoprintSnapshotBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.BUCKET}
        CorsConfiguration:
          CorsRules:
            - AllowedOrigins:
                - '*'
              AllowedHeaders:
                - '*'
              AllowedMethods:
                - GET
  Outputs:
    NewOutput:
      Description: 'Description for the output'
      Value: 'Some output value'
