service: octoprint-listener
org: andresmweber
app: my-first-app
plugins:
  - serverless-export-env
  - serverless-dotenv-plugin
  - serverless-plugin-git-variables
  - serverless-offline
  - serverless-bundle
provider:
  name: aws
  runtime: nodejs12.x
  profile: aw-serverless
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  memorySize: 512
  tags:
    GLOBAL-TAG2: bar
  environment:
    DEBUG: ${env:DEBUG, ''}
    SLS_DEBUG: ${env:SLS_DEBUG, ''}
    BUCKET: ${self:custom.BUCKET}
    REGION: ${self:provider.region}
    STAGE: ${env:STAGE, self:provider.stage}
    BASE_URL: ${self:custom.apiEndpoints.${git:branch}, self:custom.apiEndpoints.${self:provider.stage}, self:custom.resourcesStages.dev}
    SNAPSHOT_BUCKET: !Ref OctoprintSnapshotBucket
    SLACK_URL: ${ssm:/aw/slack/octoprint~true}

package:
  include:
    - lambdas/**
  exclude:
    - ./node_modules/
    - tests/**
  individually: true

custom:
  BUCKET: octoprint-listener-snapshot-${self:provider.stage}-bucket
  apiEndpoints:
    prod: https://www.example.com/api/prod
    dev: https://www.example.com/api/dev
    master: https://www.example.com/api/master


iamRoleStatements:
  - Effect: 'Allow'
    Action:
      - 's3:ListBucket'
    Resource: { 'Fn::Join': ['', ['arn:aws:s3:::', { 'Ref': 'OctoprintSnapshotBucket' }]] }
  - Effect: 'Allow'
    Action:
      - 's3:PutObject'
    Resource:
      Fn::GetAtt: [OctoprintSnapshotBucket, Arn]

functions:
  receiveWebhook:
    handler: src/lambdas/receiveWebhook.handler
    events:
      - http:
          path: webook
          method: POST
          cors: true
    environment:
      SOMETHING_ELSE: !Ref OctoprintSnapshotBucket
  getUser:
    handler: src/lambdas/getUser.handler
    events:
      - http:
          path: get-user/{ID}
          method: GET
          cors: true

# you can add CloudFormation resource templates here
resources:
  Resources:
    OctoprintSnapshotBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.BUCKET}
        CorsConfiguration:
          CorsRules:
            - AllowedOrigins:
                - '*'
              AllowedHeaders:
                - '*'
              AllowedMethods:
                - GET
  Outputs:
    NewOutput:
      Description: 'Description for the output'
      Value: 'Some output value'
