service: octoprint-listener
org: andresmweber
app: my-first-app
plugins:
  - serverless-dotenv-plugin
  - serverless-offline
  - serverless-plugin-existing-s3
  - serverless-bundle
  - serverless-plugin-git-variables
provider:
  name: aws
  runtime: nodejs12.x
  profile: aw-serverless
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  memorySize: 512
  tags:
    GLOBAL-TAG2: bar
  environment: 
    BUCKET: ${self:custom.BUCKET}
    BASE_URL: ${self:custom.apiEndpoints.${git:branch}, self:custom.apiEndpoints.${self:provider.stage}, self:custom.resourcesStages.dev}
    SNAPSHOT_BUCKET: !Ref OctoprintSnapshotBucket

custom:
  BUCKET: octoprint-listener-snapshot-${self:provider.stage}-bucket
  apiEndpoints:
    prod: https://www.example.com/api/prod
    dev: https://www.example.com/api/dev
    master: https://www.example.com/api/master
  
# you can add statements to the Lambda function's IAM Role here
iamRoleStatements:
  - Effect: "Allow"
    Action:
      - "s3:ListBucket"
    Resource: { "Fn::Join": ["", ["arn:aws:s3:::", { "Ref": "OctoprintSnapshotBucket" }]] }
  - Effect: "Allow"
    Action:
      - "s3:PutObject"
    Resource:
      Fn::GetAtt: [OctoprintSnapshotBucket, Arn]

# you can add packaging information here
package:
  include:
    - upload/**
    - lambdas/**
  exclude:
    - ./node_modules/
    - exclude-me-dir/**
    - tests/**
  individually: true

functions:
  receiveWebhook:
    handler: lambdas/receiveWebhook.handler
    events:
      - http:
          path: webook
          method: POST
          cors: true
    environment:
      SOMETHING_ELSE: !Ref OctoprintSnapshotBucket
  getUser:
    handler: lambdas/getUser.handler
    events:
      - http:
          path: get-user/{ID}
          method: GET
          cors: true

# you can add CloudFormation resource templates here
resources:
  Resources:
    OctoprintSnapshotBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.BUCKET}
        CorsConfiguration:
          CorsRules:
            - AllowedOrigins:
                - "*"
              AllowedHeaders:
                - "*"
              AllowedMethods:
                - GET
  Outputs:
    NewOutput:
      Description: "Description for the output"
      Value: "Some output value"
